apiVersion: v1
kind: Service
metadata:
  name: mock-logger
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mock-logger
---
apiVersion: v1
kind: Pod
metadata:
  name: mock-logger
  labels:
    app: mock-logger
spec:
  containers:
    - name: logger
      image: python:3.9
      command: ["python", "-u", "-c"]
      args:
        - |
          from flask import Flask, request
          app = Flask(__name__)
          @app.route('/post', methods=['POST'])
          def log():
              print("🔔 Received log:")
              print(request.get_json(force=True))
              return "ok", 200
          app.run(host="0.0.0.0", port=80)
      ports:
        - containerPort: 80
