apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          args:
            - --provider=github
            - --http-address=0.0.0.0:4180
            - --upstream=http://backend-api.default.svc.cluster.local
            - --cookie-secret=replace-this-32B-base64
            - --client-id=REPLACE_WITH_YOURS
            - --client-secret=REPLACE_WITH_YOURS
            - --redirect-url=http://localhost:4180/oauth2/callback
            - --email-domain=*
            - --set-authorization-header=true
            - --jwt-key-file=/etc/secrets/private.key
          ports:
            - containerPort: 4180
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: jwt-key
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: jwt-key
          secret:
            secretName: jwt-private-key
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4180
