apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          args:
            - --provider=github
            - --http-address=0.0.0.0:4180
            - --upstream=http://backend-api.default.svc.cluster.local
            - --scope=user:email
            - --email-domain=*
            - --client-id=Ov23li5oY0IBjJ9BPMah
            - --client-secret=28a117a77cca42b8dffa00a765970ffaa826bf22
            - --redirect-url=http://localhost:4180/oauth2/callback
            - --cookie-secret=-sLi8SX'?M"{_Om`4|}k&d,tgG:[hy>p
            - --cookie-secure=false
            - --set-authorization-header=true
            - --show-debug-on-error=true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4180